---
title: "Replication of Neural affective mechanisms predict market-level microlending by Genevsky & Knutson (2015, Psychological Science)"
author: "Lester Tong (lctong@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

This is a replication of the Internet study described in Genevsky & Knutson (2015). The original study asked about the relative contribution of different features of microloan requests to funding success. The study focused on affective features and modality, including the affective quality of the faces of the microloan recipients, and the text used in the description. The original paper found that affective ratings of microloan recipient faces in an independent Internet sample could be used to predict the rate at which a microloan received funding.


##Methods

Participants are asked to view 10 images and rate each of them on the following dimensions: how clear the image is, affective valence, affective arousal, discrete emotion, emotion intensity, and neediness.

###Power Analysis

The original analysis was a mixed-effects model, so it is not straightforward to devise an exact power analysis. Instead, I used simulation on the original data, by running the primary analysis of interest on random (without replacement) smaller subsamples of the data, I found that I could obtain power of 0.80 using samples of 2800 images.

###Planned Sample

Planned sample size is 2800 images, at 10 images per subject and 2 ratings per image, this requires a sample of 560 subjects.

###Materials

"We acquired extensive data on microloan outcomes from Kiva Microfunds (www.kiva.org), an Internet-based international microfinance organization. Kiva’s Web site allows users to offer small financial loans to individuals in need. Loans are funded in $25 increments but are received by the borrower only if the requested amount is successfully raised within 30 days of the initial loan request. We first used the Kiva application programming interface to sample 144,769 loan requests from those posted during the 2012 calendar year, the most recent period that could ensure complete loan-outcome results at the time of initial analyses. We then excluded loan requests with multiple borrowers (remaining n = 127,811), to minimize heterogeneity in photograph ratings arising from variations in the size of the borrower group; loan requests without text (remaining n = 120,130), because they could not be scored with respect to affective words in the text; (c) loan requests that were fully funded within the last 3 days of eligibility (remaining n = 109,454), to limit potential confounds due to shifts in lender’s motiva- tions and behavior as the deadline for loan expiration approached; and (d) loan requests with additional miss- ing data points (remaining n = 91,858). Of the remaining 91,858 loan requests, 13,500 were randomly sampled for analysis (i.e., 7,000 funded and 6,500 not funded)."

Note that while the original study included 7000 microloans that were funded, we are using a random subset of that original stimulus set, including 2800 stimuli.

###Procedure	

"The affective impact of the loan-request photographs was estimated by soliciting independent ratings on Ama- zon’s Mechanical Turk. All raters gave informed consent prior to participating. Each rater viewed a randomly selected photograph extracted from one of the Kiva loan requests and then evaluated the photograph on 7-point scales indexing the affective valence and arousal sig- naled by the person’s facial expression, the photograph’s identifiability (or visual clarity), and the person’s per- ceived neediness. A forced-choice question then asked raters to categorize the emotion displayed (i.e., whether the person was happy, sad, calm, fearful, angry, dis- gusted, etc.; see Fig. S1 in the Supplemental Material). To ensure that ratings referred only to the photographs and not other details on the loan-request pages, we pre- sented the photographs alone, removed from the con- text of the loan requests."

###Analysis Plan

The key analysis is as follows:

We will conduct a mixed model using random intercepts for subjects, sector, and location country code. The dependent variable will be the logarithm of the rate at which a microloan gets funded. The fixed effects will include: positive discrete emotions, negative discrete emotions, positive arousal, negative arousal, clarity of the image, perceived neediness, number of words in loan description, loan amount requested, repayment term, and requestee gender.

###Differences from Original Study

One important difference is that in the current replication, participants are explicitly asked to make 10 ratings, while in the original study, participants could choose to rate between 1 and 50 loan request images. This is not anticipated to have any directional impact on the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions
library(jsonlite)
library(tidyverse)

####Import data
## load outcome data
dana1 <- read.csv("dana1_samp.csv")
## load and process affective ratings
setwd("~/Desktop/projs/ytmt/")
hits=list.dirs(recursive=F)
##
data=list()
for (f in hits){
files=list.files(paste(f,"/production-results/", sep=""),pattern=".json")
  for (i in files){
    data[[length(data)+1]]=fromJSON(paste(f,"/production-results/",i,sep=""))
  }
}

## preprocessing will be easier when I have the data.


#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.

mod1 <- lmer(logdollarhour ~ scale(per_posemo) + scale(per_negemo) + scale(pa) + scale(na) + 
               scale(Answer.cansee) + scale(Answer.need) + 
               scale(total_words_in_description) + 
               scale(loan_amount) + scale(terms_2_repayment_term) +
               gender + (1|sector) + (1|location_3_country_code), data=dana1)


```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
